-- MySQL Script generated by MySQL Workbench
-- Mon Jun 12 14:41:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`Information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`Information` (
  `Information_ID` INT NOT NULL AUTO_INCREMENT,
  `img_path` VARCHAR(500) NULL,
  `color_path` VARCHAR(500) NULL,
  `files_path` VARCHAR(500) NULL,
  `Quote` VARCHAR(200) NULL,
  UNIQUE INDEX `Information_ID_UNIQUE` (`Information_ID` ASC),
  PRIMARY KEY (`Information_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`User` (
  `Gebruiker_ID` INT NOT NULL AUTO_INCREMENT,
  `Voornaam` VARCHAR(45) NOT NULL,
  `Achternaam` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Wachtwoord` VARCHAR(256) NOT NULL,
  `Student_nr.` VARCHAR(45) NULL,
  `Verified` TINYINT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Information_ID` INT NOT NULL,
  PRIMARY KEY (`Gebruiker_ID`),
  UNIQUE INDEX `Gebruiker_ID_UNIQUE` (`Gebruiker_ID` ASC),
  UNIQUE INDEX `Student_nr._UNIQUE` (`Student_nr.` ASC),
  INDEX `fk_User_Information1_idx` (`Information_ID` ASC),
  CONSTRAINT `fk_User_Information1`
    FOREIGN KEY (`Information_ID`)
    REFERENCES `portfolio`.`Information` (`Information_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`Bericht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`Bericht` (
  `Bericht_ID` INT NOT NULL AUTO_INCREMENT,
  `Datum_tijd` DATETIME NOT NULL,
  `Bericht` VARCHAR(500) NOT NULL,
  `Information_ID` INT NOT NULL,
  PRIMARY KEY (`Bericht_ID`),
  INDEX `fk_Bericht_Information_idx` (`Information_ID` ASC),
  CONSTRAINT `fk_Bericht_Information`
    FOREIGN KEY (`Information_ID`)
    REFERENCES `portfolio`.`Information` (`Information_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`Contact` (
  `Contactg_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(100) NOT NULL,
  `Naam` VARCHAR(100) NOT NULL,
  `Onderwerp` VARCHAR(50) NOT NULL,
  `Bericht` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`Contactg_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
